api:
  build: .
  dockerfile: Dockerfile
  env_file: .env
  command: mix do ecto.create, ecto.migrate, phoenix.server
  environment:
    - MIX_ENV=dev
    - PORT=4000
    - PG_HOST=postgres
    - PG_USERNAME=postgres
  volumes:
    - .:/app
  ports:
    - "4000:4000"
  links:
    - postgres

postgres:
  image: postgres:9.6
  ports:
    - "5432"
